/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.iesalb.dam2.di.jasc.tema1.proyecto;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author Jose Antonio
 */
public class VistaProductoModal extends java.awt.Dialog {

        /**Producto que estamos visualizando */
      private final Productos producto;
      private boolean isAceptado = false ;
      private JComboBox combo;
    /**
     * Creates new form VistaProducto1
     */
    public VistaProductoModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //como no recibo contacto como argumento, creo uno vacio
        producto = new Productos();
        combo = new JComboBox();
        combo.addItem("Unidad");
        combo.addItem("Litros");
        combo.addItem("Kilos");
    }
    
    public VistaProductoModal(java.awt.Frame parent, boolean modal,Productos producto){
        super(parent, modal);
        initComponents();
        
        
        //Asignar al formulario el contacto que se va a editar
        this.producto = producto;
        
        // Cargar el fomulario con los datos del producto
        textCodigo.setText(producto.getCodigo());
        textNombre.setText(producto.getNombre());
        textDescripcion.setText(producto.getDescripcion());
        textPrecio.setText(Double.toString(producto.getPrecioUnitario()));
        textCantidad.setText(Double.toString(producto.getCantidad()));
        comboCantidad.addItem(producto.getMedida());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        labelTitulo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        buttonAceptar = new javax.swing.JButton();
        buttonCancerlar = new javax.swing.JButton();
        panelFormalario = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        lableDescripcion = new javax.swing.JLabel();
        lablePrecio = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textDescripcion = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        comboCantidad = new javax.swing.JComboBox<>();
        textCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setBackground(java.awt.Color.darkGray);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));
        setTitle("Añadir o Editar Producto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 0, 51));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("PRODUCTO");
        add(labelTitulo, java.awt.BorderLayout.NORTH);

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });
        panelBotones.add(buttonAceptar);

        buttonCancerlar.setText("Cancelar");
        buttonCancerlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancerlarActionPerformed(evt);
            }
        });
        panelBotones.add(buttonCancerlar);

        add(panelBotones, java.awt.BorderLayout.SOUTH);

        panelFormalario.setPreferredSize(new java.awt.Dimension(400, 200));

        labelCodigo.setText("Codigo");

        labelNombre.setText("Nombre");

        lableDescripcion.setText("Descripcion");

        lablePrecio.setText("Precio");

        labelCantidad.setText("Cantidad");

        textDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescripcionActionPerformed(evt);
            }
        });

        comboCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "Kilos", "Litros" }));
        comboCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCantidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        javax.swing.GroupLayout panelFormalarioLayout = new javax.swing.GroupLayout(panelFormalario);
        panelFormalario.setLayout(panelFormalarioLayout);
        panelFormalarioLayout.setHorizontalGroup(
            panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormalarioLayout.createSequentialGroup()
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormalarioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lablePrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCantidad, 0, 265, Short.MAX_VALUE)
                            .addComponent(textCantidad)
                            .addComponent(textPrecio)))
                    .addGroup(panelFormalarioLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableDescripcion)
                            .addComponent(labelNombre)
                            .addComponent(labelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(textDescripcion)
                            .addComponent(textCodigo))))
                .addGap(22, 22, 22))
        );
        panelFormalarioLayout.setVerticalGroup(
            panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormalarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lablePrecio)
                    .addComponent(textPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGroup(panelFormalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFormalarioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelCantidad))
                    .addGroup(panelFormalarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboCantidad)))
                .addGap(42, 42, 42))
        );

        add(panelFormalario, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        
        //se oculta el formulario y lo libero
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        // TODO add your handling code here:
        
        //Indico que se ha pulsado en aceptar
        isAceptado = true;
        
        //Asignar los valores en el fomurlario al objeto
        producto.setCodigo(textCodigo.getText());
        producto.setNombre(textNombre.getText());
        producto.setDescripcion(textDescripcion.getText());
        producto.setPrecioUnitario(Double.parseDouble(textPrecio.getText()));
        producto.setCantidad(Double.parseDouble(textCantidad.getText()));
        producto.setMedida(comboCantidad.getSelectedItem().toString());
        //Se oculta el formulario y lo libero
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void textDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDescripcionActionPerformed

    private void buttonCancerlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancerlarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancerlarActionPerformed

    private void comboCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaProductoModal dialog = new VistaProductoModal(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonCancerlar;
    private javax.swing.JComboBox<String> comboCantidad;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lableDescripcion;
    private javax.swing.JLabel lablePrecio;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFormalario;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textDescripcion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables

    /**
     * si returna trye es que se ha salidp pulsando en aceptar
     * @return 
     */
    
    public Productos getProducto(){
        return isAceptado?producto:null;
    }

}

